### ISSUE TITLE
Missing openshift model attributes

### ISSUE THREAD

**Issue by slemrmartin** [ManageIQ/topological_inventory-ingress_api-client-ruby#20]
Some generated attributes are missing (openshift parser defines it and then returns nil => brokes mock-collector specs):
- `TopologicalInventory::IngressApi::Client::ContainerGroup.ipaddress`
- `TopologicalInventory::IngressApi::Client::ServiceInstance.service_plan`
- - there is `service_parameters_set` instead
- `TopologicalInventory::IngressApi::Client::ServicePlan.resource_version`

@agrare

**Comment by agrare** [comment]
Fixed by https://github.com/ManageIQ/topological_inventory-ingress_api/pull/27
